ManageWikiDefaultPermissions: fix description i18n
miraheze/ManageWiki pull request #443
Opened 2024-01-27 21:15 UTC by RhinosF1

2024-01-27 21:24 UTC, RhinosF1 commented
Hmm, I'm not sure if it was ever meant to be 2 messages. It looks like the description may have at one point before the i18n got lost intended to change between norights and rights.

@Universal-Omega: do you recall the history?

2024-01-27 21:57 UTC, OAuthority commented
One of the messages is to show if the user doesn't have the right to manage default permissions (or I guess, now reset the cache etc.) 

It's probably easier to just do a conditional check whether the user has the rights or not and list is accordingly.

2024-02-04 17:44 UTC, redbluegreenhat commented
That message is from WikiForge, and has never existed in ManageWiki before. It was introduced in #438. I'd like to say we can just get rid of it and return managewikidefaultpermissions only.

2024-02-04 17:47 UTC, redbluegreenhat requested changes

2024-02-04 17:47 UTC, redbluegreenhat commented on includes/Specials/SpecialManageWikiDefaultPermissions.php
> +		return $this->msg( $this->canModify() ? 'managewikidefaultpermissions' : 'managewikidefaultpermissions' )->text();
```suggestion
		return $this->msg( 'managewikidefaultpermissions' )->text();
```

2024-02-04 17:56 UTC, redbluegreenhat commented
I get that message now, just like how Special:ManageWiki/extensions is titled "View this wiki's extensions" for users without permissions to edit it, and "Manage this wiki's extensions" for users that do have them, this does the same but for Special:ManageWikiDefaultPermissions. We're going to be keeping it, I'll make another PR adding that message to i18n.

2024-02-04 17:56 UTC, closed without merging